[build]
  command = "npm run production && hugo --gc --minify -b $URL --themesDir ../../"
  base    = "exampleSite"
  publish = "exampleSite/public"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_VERSION = "0.62.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --themesDir ../../"

[context.branch-deploy]
  command = "npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL --themesDir ../../"
