DefaultContentLanguage = "en"
title = "Hugo Solstice Theme"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
googleAnalytics = ""
#disableKinds = ["taxonomy", "taxonomyTerm"]

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "Eclipse Foundation: Solstice theme for Hugo."
  subtitle = "Eclipse Foundation"
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["hugo", "solstice", "eclipse foundation"]
#  logo = "images/logo/eclipse-foundation-white.svg"
#  favicon = "images/favicon.ico"
  styles = "css/styles.css"
  js = "js/solstice.js"
  gcse = ""
  header_wrapper_class = "header-default-bg-img"
  call_for_action_text = "Download"
  call_for_action_url = "/downloads"
  call_for_action_icon = "fa-download"
  show_events = true
  table_classes = "table table-bordered"
  hide_cfa_same_page = true
  show_collapsible_menu = true
  sidebar_layout = "default"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"
  technology_types = "technology_types"
  build_technologies = "build_technologies"
  other_tags = "other_tags"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
