
[[main]]
    name = "Exemples"
    url = "#"
    weight = 2
    identifier = "examples"
    
[[main]]
    name = "Page seule"
    url = "/single_page/"
    weight = 1
    parent = "examples"
    
[[main]]
    name = "Exemples de nouvelles"
    url = "/news/"
    weight = 2
    parent = "examples"
    
[[main]]
    name = "Exemples de Membres"
    url = "/membership/"
    weight = 3
    parent = "examples"
    
[[main]]
    name = "Exemples d'événements"
    url = "/events/"
    weight = 3
    parent = "examples"

[[main]]
    name = "Exemples de FAQ"
    url = "/faq/"
    weight = 4
    parent = "examples"

[[main]]
    name = "Hide Call For Action"
    url = "/hide_call_for_action/"
    weight = 5
    parent = "examples"

[[main]]
    name = "Without Breadcrumb"
    url = "/without_breadcrumb/"
    weight = 6
    parent = "examples"

[[main]]
    name = "multi-children mobile sidebar sample"
    url = "/third-parent/"
    weight = 7
    parent = "examples"

[[main]]
    name = "Custom Jumbotron"
    url = "/custom-jumbotron/"
    weight = 8
    parent = "examples"

[[main]]
    name = "Composantes"
    url = "/components/"
    weight = 3
    identifier = "components"

[[main]]
    name = "Solstice Additions"
    url = "/components/#solstice"
    weight = 1
    parent = "components"
    identifier = "solstice"

[[main]]
    name = "Events Framework"
    url = "/components/#events-framework"
    weight = 2
    parent = "components"
    identifier = "events"

[[main]]
    name = "Dynamic Content"
    url = "/components/#dynamic"
    weight = 3
    parent = "components"
    identifier = "dynamic"

[[main]]
    name = "Deprecated"
    url = "/components/#deprecated"
    weight = 4
    parent = "components"
    identifier = "deprecated"

[[main]]
    name = "Membres"
    url = "/components/members/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "Liste de taxonomie"
    url = "/components/taxonomy_list/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "Témoignages"
    url = "/components/testimonials/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "Vidéos Youtube"
    url = "/components/youtube/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "FAQ"
    url = "/components/faq/"
    weight = 4
    parent = "solstice"

[[main]]
    name = "Pied de page en vedette"
    url = "/components/featured_footer/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "Article en vedette"
    url = "/components/featured_story/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "Liste de projects"
    url = "/components/project_list/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "Liste de projects d'EclipseFdn"
    url = "/components/eclipsefdn_projects/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "Tableaux HTML"
    url = "/components/tables/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "Text Target"
    url = "/components/text_target/"
    weight = 3
    parent = "solstice"

[[main]]
    name = "RSS Feed"
    url = "/components/rss/"
    weight = 3
    parent = "dynamic"

[[main]]
    name = "Users Display [fr]"
    url = "/components/user_display/"
    weight = 3
    parent = "events"
    
[[main]]
    name = "User Bios [fr]"
    url = "/components/user_bios/"
    weight = 3
    parent = "events"
    
[[main]]
    name = "Registration [fr]"
    url = "/components/registration/"
    weight = 3
    parent = "events"
    
[[main]]
    name = "Ordre du jour"
    url = "/components/agenda/"
    weight = 3
    parent = "events"
    
[[main]]
    name = "Newsroom News"
    url = "/components/agenda/"
    weight = 3
    parent = "dynamic"
    
[[main]]
    name = "Newsroom Events"
    url = "/components/agenda/"
    weight = 3
    parent = "dynamic"

[[main]]
    name = "Nouvelles"
    url = "/components/news/"
    weight = 2
    parent = "deprecated"

[[main]]
    name = "Événements"
    url = "/components/events/"
    weight = 3
    parent = "deprecated"

[[sidebar]]
    name = "Thème Solstice d'Hugo"
    url = "#"
    weight = 2
    identifier = "home"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    
[[sidebar]]
    name = "Liste des composantes"
    url = "/components"
    weight = 1
    parent = "home"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"

    
[[sidebar]]
    name = "Page GitHub"
    url = "https://github.com/EclipseFdn/hugo-solstice-theme"
    weight = 2
    parent = "home"
    pre = "<i class=\"fa fa-github fa-fw\"></i>"

[[sidebar]]
    name = "Translation Guide" 
    url = "/translations"
    weight = 3
    parent = "home"

[[sidebar]]
    name = "Translation Guide 1" 
    url = "/translations"
    weight = 1
    parent = "translation-guide"
    
[[sidebar]]
    name = "Translation Guide 2" 
    url = "/translations"
    weight = 1
    parent = "translation-guide"

[[sidebar]]
    name = "Third parent"
    url = "/third-parent"
    weight = 2
    pre = "<i class=\"sidebar-menu-icon\" data-feather=\"github\"></i>"
    identifier = "third-parent"

[[sidebar]]
    name = "Test Children"
    url = "/third-parent/test-children"
    weight = 1
    parent = "third-parent"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    identifier = "test-children"

[[sidebar]]
    name = "Test Children 2"
    url = "/third-parent/test-children-2"
    weight = 1
    parent = "third-parent"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    identifier = "test-children-2"

[[sidebar]]
    name = "Test Children Children 1"
    url = "/third-parent/test-children/test-children-children"
    weight = 1
    parent = "test-children"

[[sidebar]]
    name = "Test Children Children 2"
    url = "/third-parent/test-children/test-children-children-2"
    weight = 2
    parent = "test-children"

[[sidebar]]
    name = "Premier article"
    url = "#"
    weight = 1
    parent = "membership"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"

    
[[sidebar]]
    name = "Deuxième article"
    url = "#"
    weight = 2
    parent = "membership"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    
